### ISSUE TITLE
Address Collection Resource Misnomer

### ISSUE THREAD

**Issue by fosrias** [ionwg/ion-doc#2]
There is no such thing as a collection resource. Rails bad conventions. Thus, should not have a separate media-type and resolve this as a resource and look into using IANA `item` or other options.

**Comment by lhazlewood** [comment]
Closing the loop on this - I'll update the current ion-doc to reflect a single media type declaration.  Any objections to closing this issue?

**Comment by fosrias** [comment]
Fine with me.

**Comment by lhazlewood** [comment]
Closed.  New discussion around this can be opened as a new issue.
