### ISSUE TITLE
Double statement

### ISSUE THREAD

**Issue by davidsowerby** [ionwg/ion-doc#21]
"If a member name is equal to the case-sensitive octet sequence meta and the member value **is an empty JSON Object with no members**, an Ion parser MUST NOT identify the member as a Meta Object."

Suggest deleting "with no members"  as it is the same as "empty" (or delete "empty")

**Comment by lhazlewood** [comment]
Thanks for the issue!  Please see the latest doc w/ `meta` removed and let us know if you see any more duplicates.  I'm personally grateful that you're digging through this in detail!

(based on the `meta` removal, I'm closing this issue, but feel free to re-open if you think it's necessary still)
