### ISSUE TITLE
Address query parameters, body parameters and forms

### ISSUE THREAD

**Issue by fosrias** [ionwg/ion-doc#3]
Initially, address these generically not considering URI templates (which should be discouraged in hypermedia). Once we can clarify how to specify these, address expanding to URI templates.

**Comment by lhazlewood** [comment]
Totally agree on this btw.  We're doing this same kind of definitions at Stormpath to enforce a consistent web protocol between our JS and mobile SDKs and any of our server-side SDKs (i.e. an Angular app should be able to communicate with our SDK running in a Node.js app and with our Java SDK running in a Java app without any changes).  

It makes total sense to me to define these things in an HTTP 'profile' of Ion like what might result from issue #4.

**Comment by lhazlewood** [comment]
@fosrias and @smizell I believe this is largely addressed by the new Forms part.  Please see here:

https://github.com/ionwg/ion-doc/pull/15

and the current draft reflects this:

http://ionwg.github.io/draft-ion.html

Questions/comments welcome as always.

**Comment by lhazlewood** [comment]
Just an update.  The Forms section of the document still needs to address form submission semantics (i.e. in a POST, the POST body format, w/ a GET how query parameters are added)

**Comment by lhazlewood** [comment]
This has been addressed in the current draft at https://ionwg.org.  Please open a new issue to address any specific form semantics.  Thanks!
