### ISSUE TITLE
Meta Attributes and Meta Links

### ISSUE THREAD

**Issue by smizell** [ionwg/ion-doc#8]
It would be good to think about how meta attributes and meta links can be specified in the message. A use case of this would be a "profile" link.

**Comment by lhazlewood** [comment]
@smizell do you think this issue is being covered in #4 ?  If so, can we close this issue?  If not, could you please elaborate as to what might be different? Thanks!

**Comment by lhazlewood** [comment]
Oops, I meant #1 - I changed the text above to reflect that ^^

**Comment by lhazlewood** [comment]
@smizell I think this can be closed out unless you'd like to add a new member to the member registry?

**Comment by smizell** [comment]
Let's close it! :)
